services:
  redis:
    image: redis:6.0.5
    container_name: redis
    privileged: true
    expose:
      - 6379
    # volumes:
    #   - /root/docker/redis/data:/data
    #   - /root/docker/redis/conf/redis.conf:/etc/redis/redis.conf
    ports:
      - 6379:6379
    command: redis-server --appendonly yes --requirepass "yueliminvc@outlook.com"
