services:
  namesrv:
    image: apacherocketmq/rocketmq
    container_name: rmqnamesrv
    ports:
      - 9876:9876
    volumes:
      - D:/docker/rocketmq/namesrv/logs:/home/rocketmq/logs
    command: sh mqnamesrv
  broker:
    image: apacherocketmq/rocketmq
    container_name: rmqbroker
    ports:
      - 10909:10909
      - 10911:10911
      - 10912:10912
    volumes:
      - D:/docker/rocketmq/broker/logs:/home/rocketmq/logs
      - D:/docker/rocketmq/broker/store:/home/rocketmq/store
      - D:/docker/rocketmq/broker/conf/broker.conf:/home/rocketmq/conf/broker.conf
    environment:
      NAMESRV_ADDR: "namesrv:9876"
      JAVA_OPTS: " -Duser.home=/opt"
      JAVA_OPT_EXT: "-server -Xms128m -Xmx128m -Xmn128m"
    command: sh mqbroker -n namesrv:9876 -c ../conf/broker.conf
    depends_on:
      - namesrv
  rmqconsole:
    image: styletang/rocketmq-console-ng
    container_name: rmqconsole
    ports:
      - 18080:8080
    environment:
      JAVA_OPTS: "-Drocketmq.namesrv.addr=namesrv:9876 -Dcom.rocketmq.sendMessageWithVIPChannel=false"
    depends_on:
      - namesrv
