services:
  es:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.4.0
    container_name: es
    restart: always
    ports:
      - 9200:9200
      - 9300:9300
    environment:
      - cluster.name=sky-walking-es
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms256m -Xmx256m"
      - TZ=Asia/Shanghai
    # volumes:
    #   - /root/docker/elasticsearch/logs:/usr/share/elasticsearch/logs
    #   - /root/docker/elasticsearch/data:/usr/share/elasticsearch/data
    #   - /root/docker/elasticsearch/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
    ulimits:
      memlock:
        soft: -1
        hard: -1

  oap:
    image: apache/skywalking-oap-server:6.5.0
    container_name: oap
    depends_on:
      - es
    links:
      - es
    restart: always
    ports:
      - 11800:11800
      - 12800:12800
    environment:
      SW_STORAGE: elasticsearch
      SW_STORAGE_ES_CLUSTER_NODES: es:9200
      TZ: Asia/Shanghai

  ui:
    image: apache/skywalking-ui:6.5.0
    container_name: ui
    depends_on:
      - oap
    links:
      - oap
    restart: always
    ports:
      - 8080:8080
    environment:
      SW_OAP_ADDRESS: oap:12800
      TZ: Asia/Shanghai
