services:
  minio:
    image: minio/minio:RELEASE.2020-08-26T00-00-49Z
    container_name: minio
    privileged: true
    # volumes:
    #   - /root/docker/minio/data:/data
    ports:
      - "9000:9000"
    environment:
      MINIO_ACCESS_KEY: minio
      MINIO_SECRET_KEY: yueliminvc@outlook.com
    command: server /data
    healthcheck:
      test:
        [
          "CMD",
          "curl",
          "-f",
          "http://localhost:9000/minio/health/live"
        ]
      interval: 30s
      timeout: 20s
      retries: 3
